config/routes.rb
Rails.application.routes.draw do
  resources :breeds, only: %i[index show]
  resources :horses, only: :show do
    collection do
      get :search
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'breeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :horses
end

app/models/horse.rb
class Horse < ApplicationRecord
  belongs_to :breed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: %i[show edit update destroy]

  # GET /breeds or /breeds.json
  def index
    # @breeds = Breed.all
    @breeds = Breed.order(:name)
  end

  # GET /breeds/1 or /breeds/1.json
  def show
    @breed = Breed.find(params[:id])
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit; end

  # POST /breeds or /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to breed_url(@breed), notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1 or /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to breed_url(@breed), notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1 or /breeds/1.json
  def destroy
    @breed.destroy!

    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_breed
    @breed = Breed.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def breed_params
    params.require(:breed).permit(:name)
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: %i[show edit update destroy]

  # GET /horses or /horses.json
  def index
    # @horses = Horse.all
    @horse = Horse.find(params[:id])
  end

  # GET /horses/1 or /horses/1.json
  def show; end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/search?keywords=user+search+terms
  def search
    @horses = Horse.where('name LIKE ?', "%#{params[:search_term]}%")
  end

  # GET /horses/1/edit
  def edit; end

  # POST /horses or /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to horse_url(@horse), notice: 'Horse was successfully created.' }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1 or /horses/1.json
  def update
    respond_to do |format|
      if @horse.update(horse_params)
        format.html { redirect_to horse_url(@horse), notice: 'Horse was successfully updated.' }
        format.json { render :show, status: :ok, location: @horse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1 or /horses/1.json
  def destroy
    @horse.destroy!

    respond_to do |format|
      format.html { redirect_to horses_url, notice: 'Horse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_horse
    @horse = Horse.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def horse_params
    params.require(:horse).permit(:name, :age, :number_of_legs, :top_speed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/views/breeds/_breed.html.erb
<div id="<%= dom_id breed %>">
  <p>
    <strong>Name:</strong>
    <%= breed.name %>
  </p>

</div>

app/views/breeds/_form.html.erb
<%= form_with(model: breed) do |form| %>
  <% if breed.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
        <% breed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing breed</h1>

<%= render "form", breed: @breed %>

<br>

<div>
  <%= link_to "Show this breed", @breed %> |
  <%= link_to "Back to breeds", breeds_path %>
</div>

app/views/breeds/index.html.erb
<h3 class="title is-4">All Horse Breeds</h3>

<% @breeds.each do |breed| %>
  <p><%= link_to breed.name, breed %></p>
<% end %>

app/views/breeds/new.html.erb
<h1>New breed</h1>

<%= render "form", breed: @breed %>

<br>

<div>
  <%= link_to "Back to breeds", breeds_path %>
</div>

app/views/breeds/show.html.erb
<h3 class="title is-4"><%= @breed.name %></h3>

<h4 class="title is-5">Horses of this breed</h4>

<div class="columns is-multiline">
  <%= render partial: 'horses/horse',
             collection: @breed.horses,
             locals: { show_link: true } %>
</div>

app/views/horses/_form.html.erb
<%= form_with(model: horse) do |form| %>
  <% if horse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
        <% horse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :number_of_legs, style: "display: block" %>
    <%= form.number_field :number_of_legs %>
  </div>

  <div>
    <%= form.label :top_speed, style: "display: block" %>
    <%= form.text_field :top_speed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/horses/_horse.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <p class="title">
        <% if show_link %>
          <%= link_to horse.name, horse %>
        <% else %>
          <%= horse.name %>
        <% end %>
      </p>
      <p>Breed: <%= link_to horse.breed.name, horse.breed %></p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        Age: <br><%= horse.age %>
      </p>
      <p class="card-footer-item">
        Legs: <br><%= horse.number_of_legs %>
      </p>
      <p class="card-footer-item">
        Speed: <br><%= horse.top_speed.round(2) %>
      </p>
    </footer>
  </div>
</div>

app/views/horses/edit.html.erb
<h1>Editing horse</h1>

<%= render "form", horse: @horse %>

<br>

<div>
  <%= link_to "Show this horse", @horse %> |
  <%= link_to "Back to horses", horses_path %>
</div>

app/views/horses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Horses</h1>

<div id="horses">
  <% @horses.each do |horse| %>
    <%= render horse %>
    <p>
      <%= link_to "Show this horse", horse %>
    </p>
  <% end %>
</div>

<%= link_to "New horse", new_horse_path %>

app/views/horses/new.html.erb
<h1>New horse</h1>

<%= render "form", horse: @horse %>

<br>

<div>
  <%= link_to "Back to horses", horses_path %>
</div>

app/views/horses/search.html.erb
<p>
  Found <%= pluralize(@horses.size, 'result') %>
  for the search term "<%= params[:search_term] %>".
</p>

<div class="search-results columns is-multiline">
  <%= render partial: 'horses/horse',
             collection: @horses,
             locals: { show_link: true } %>
</div>

app/views/horses/show.html.erb
<div class="columns">
  <%= render partial: 'horse',
             object: @horse,
             locals: { show_link: false } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HorsesOnRails202324</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="container">
        <header>
          <h1 class="title is-1"><%= link_to 'Horses on Rails', root_path %></h1>
          <h2 class="subtitle is-4">Look at all the pretty horses standing in a <strong>row, row, row</strong>.</h2>
        </header>
        <%= render partial: 'shared/search_form' %>
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/shared/_search_form.html.erb
<%= form_with(url: search_horses_path, local: true, method: "get", class: 'mt-5 mb-5') do %>
  <div class="field has-addons">
    <div class="control">
      <%= text_field_tag(:search_term, nil, class: 'input', placeholder: 'Search Horses By Name') %>
    </div>
    <div class="control">
      <%= submit_tag("Search", class: "button is-info") %>
    </div>
  </div>
<% end %>